# Generated by Django 5.2 on 2025-05-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
