# Generated by Django 5.2 on 2025-05-05 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_userprofile_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sandwich",
            name="bread",
        ),
        migrations.RemoveField(
            model_name="sandwich",
            name="cheeses",
        ),
        migrations.DeleteModel(
            name="Chips",
        ),
        migrations.RemoveField(
            model_name="sandwich",
            name="condiments",
        ),
        migrations.DeleteModel(
            name="Drink",
        ),
        migrations.RemoveField(
            model_name="sandwich",
            name="proteins",
        ),
        migrations.RemoveField(
            model_name="sandwich",
            name="toppings",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Bread",
        ),
        migrations.DeleteModel(
            name="Cheese",
        ),
        migrations.DeleteModel(
            name="Condiment",
        ),
        migrations.DeleteModel(
            name="Protein",
        ),
        migrations.DeleteModel(
            name="Sandwich",
        ),
        migrations.DeleteModel(
            name="Topping",
        ),
    ]
